# Generated by Django 5.1.5 on 2025-02-03 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("funeral", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="고객명")),
                ("phone", models.CharField(max_length=20, verbose_name="전화번호")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="이메일"),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "고객",
                "verbose_name_plural": "고객 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemorialRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="추모실명")),
                ("capacity", models.IntegerField(verbose_name="수용인원")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="사용가능여부")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "추모실",
                "verbose_name_plural": "추모실 목록",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="반려동물명")),
                ("species", models.CharField(max_length=50, verbose_name="종")),
                (
                    "breed",
                    models.CharField(blank=True, max_length=100, verbose_name="품종"),
                ),
                ("age", models.IntegerField(verbose_name="나이")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="체중"
                    ),
                ),
                ("death_date", models.DateTimeField(verbose_name="사망일시")),
                (
                    "death_reason",
                    models.CharField(
                        choices=[
                            ("natural", "자연사"),
                            ("disease", "병사"),
                            ("accident", "사고사"),
                            ("euthanasia", "안락사"),
                        ],
                        max_length=20,
                        verbose_name="사망사유",
                    ),
                ),
                ("special_notes", models.TextField(blank=True, verbose_name="특이사항")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="reservations.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "반려동물",
                "verbose_name_plural": "반려동물 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_at", models.DateTimeField(verbose_name="예약일시")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("confirmed", "확정"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "is_emergency",
                    models.BooleanField(default=False, verbose_name="긴급여부"),
                ),
                (
                    "visit_route",
                    models.CharField(
                        choices=[
                            ("internet", "인터넷"),
                            ("blog", "블로그"),
                            ("hospital", "병원"),
                            ("referral", "지인소개"),
                        ],
                        max_length=20,
                        verbose_name="방문경로",
                    ),
                ),
                (
                    "referral_hospital",
                    models.CharField(blank=True, max_length=100, verbose_name="경유병원"),
                ),
                (
                    "need_death_certificate",
                    models.BooleanField(default=False, verbose_name="장례확인서필요여부"),
                ),
                ("custom_requests", models.TextField(blank=True, verbose_name="요청사항")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.customer",
                    ),
                ),
                (
                    "memorial_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.memorialroom",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="funeral.funeralpackage",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약",
                "verbose_name_plural": "예약 목록",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("confirmed", "확정"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        max_length=20,
                        verbose_name="이전상태",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기중"),
                            ("confirmed", "확정"),
                            ("in_progress", "진행중"),
                            ("completed", "완료"),
                            ("cancelled", "취소"),
                        ],
                        max_length=20,
                        verbose_name="변경상태",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약 이력",
                "verbose_name_plural": "예약 이력 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["status", "scheduled_at"], name="reservation_status_894572_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["customer", "status"], name="reservation_custome_e440be_idx"
            ),
        ),
    ]
