# Generated by Django 5.1.5 on 2025-02-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="death_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="사망일시"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="death_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("natural", "자연사"),
                    ("disease", "병사"),
                    ("accident", "사고사"),
                    ("euthanasia", "안락사"),
                ],
                max_length=20,
                null=True,
                verbose_name="사망사유",
            ),
        ),
    ]
