# Generated by Django 5.1.5 on 2025-02-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_pet_death_date_alter_pet_death_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[("male", "수컷"), ("female", "암컷")],
                default="male",
                max_length=10,
                verbose_name="성별",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="is_neutered",
            field=models.BooleanField(default=False, verbose_name="중성화 여부"),
        ),
    ]
