# Generated by Django 5.1.5 on 2025-02-08 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funeral", "0001_initial"),
        ("memorial_rooms", "0002_alter_memorialroom_operating_hours"),
        ("reservations", "0003_pet_gender_pet_is_neutered"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="memorial_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="memorial_rooms.memorialroom",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="나이"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "수컷"), ("female", "암컷")],
                max_length=10,
                null=True,
                verbose_name="성별",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="종"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="체중"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="funeral.funeralpackage",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="예약일시"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="visit_route",
            field=models.CharField(
                blank=True,
                choices=[
                    ("internet", "인터넷"),
                    ("blog", "블로그"),
                    ("hospital", "병원"),
                    ("referral", "지인소개"),
                ],
                max_length=20,
                null=True,
                verbose_name="방문경로",
            ),
        ),
        migrations.DeleteModel(name="MemorialRoom",),
    ]
