# Generated by Django 5.1.5 on 2025-02-12 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funeral", "0001_initial"),
        ("memorial_rooms", "0002_alter_memorialroom_operating_hours"),
        (
            "reservations",
            "0005_reservation_cancel_notes_reservation_cancel_reason_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="reservations.customer",
                verbose_name="고객",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="assigned_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당 직원",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_reservations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.customer",
                verbose_name="고객",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="memorial_room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="memorial_rooms.memorialroom",
                verbose_name="추모실",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="funeral.funeralpackage",
                verbose_name="장례 패키지",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="reservations.pet",
                verbose_name="반려동물",
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="처리자",
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="histories",
                to="reservations.reservation",
                verbose_name="예약",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="reservation_phone_63f42b_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["name", "phone"], name="reservation_name_465ed2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(
                fields=["customer", "name"], name="reservation_custome_424d09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(
                fields=["death_date"], name="reservation_death_d_ec34c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["assigned_staff", "status"],
                name="reservation_assigne_705244_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservationhistory",
            index=models.Index(
                fields=["reservation", "-created_at"],
                name="reservation_reserva_497f01_idx",
            ),
        ),
    ]
