# Generated by Django 5.1.5 on 2025-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0006_alter_pet_customer_alter_reservation_assigned_staff_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MemorialRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="추모실 이름")),
                ("capacity", models.IntegerField(default=10, verbose_name="수용 인원")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("available", "사용가능"),
                            ("in_use", "사용중"),
                            ("reserved", "예약중"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="현재 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "추모실",
                "verbose_name_plural": "추모실 목록",
                "ordering": ["name"],
            },
        ),
    ]
