# Generated by Django 5.1.5 on 2025-02-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0007_memorialroom"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorialroom",
            name="operating_hours",
            field=models.JSONField(
                default=dict,
                help_text='{"start_time": "HH:MM", "end_time": "HH:MM"} 형식',
                verbose_name="운영 시간",
            ),
        ),
    ]
