# Generated by Django 5.1.5 on 2025-02-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funeral", "0001_initial"),
        ("reservations", "0009_alter_reservationhistory_changed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="additional_options",
            field=models.ManyToManyField(
                blank=True,
                related_name="reservations",
                to="funeral.additionaloption",
                verbose_name="추가 옵션",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="premium_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="funeral.premiumline",
                verbose_name="프리미엄 라인",
            ),
        ),
    ]
