# Generated by Django 5.1.5 on 2025-02-20 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funeral", "0001_initial"),
        ("memorial_rooms", "0003_memorialroom_current_status"),
        ("reservations", "0011_remove_pet_special_notes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="block_end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="블록 종료 시간"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="완료일시"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="블록 처리 여부"),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["is_blocked", "block_end_time"],
                name="reservation_is_bloc_9a4553_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["completed_at"], name="reservation_complet_24eff9_idx"
            ),
        ),
    ]
