# Generated by Django 5.1.5 on 2025-02-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_supplier_notes_alter_purchaseorder_created_at"),
        (
            "reservations",
            "0012_reservation_block_end_time_reservation_completed_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservationInventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="사용 수량")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservation_usages",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items_used",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "verbose_name": "예약 사용 재고",
                "verbose_name_plural": "예약 사용 재고 목록",
                "unique_together": {("reservation", "inventory_item")},
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="inventory_items",
            field=models.ManyToManyField(
                related_name="reservations",
                through="reservations.ReservationInventoryItem",
                to="inventory.inventoryitem",
                verbose_name="사용된 재고",
            ),
        ),
    ]
