# Generated by Django 5.1.5 on 2025-02-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservationinventoryitem_reservation_inventory_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', '정률'), ('fixed', '정액'), (None, '없음')], help_text='할인 유형 (정률/정액)', max_length=10, null=True, verbose_name='할인 유형'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='할인율(%) 또는 할인금액', max_digits=10, null=True, verbose_name='할인 값'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='weight_surcharge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='무게로 인한 추가 요금', max_digits=10, verbose_name='무게 할증료'),
        ),
    ]
