# Generated by Django 5.1.5 on 2025-02-27 04:07

import reservations.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations",
            "0014_reservation_discount_type_reservation_discount_value_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer", name="reservation_phone_63f42b_idx",
        ),
        migrations.RemoveIndex(
            model_name="customer", name="reservation_name_465ed2_idx",
        ),
        migrations.RemoveIndex(
            model_name="pet", name="reservation_custome_424d09_idx",
        ),
        migrations.RemoveIndex(
            model_name="pet", name="reservation_death_d_ec34c7_idx",
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=reservations.fields.EncryptedTextField(blank=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=reservations.fields.EncryptedEmailField(
                blank=True, max_length=254, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=reservations.fields.EncryptedCharField(
                max_length=100, verbose_name="고객명"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=reservations.fields.EncryptedCharField(
                max_length=20, verbose_name="전화번호"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=reservations.fields.EncryptedCharField(
                blank=True, max_length=100, verbose_name="품종"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=reservations.fields.EncryptedCharField(
                max_length=100, verbose_name="반려동물명"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="species",
            field=reservations.fields.EncryptedCharField(
                blank=True, max_length=50, null=True, verbose_name="종"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["-created_at"], name="reservation_created_7eab0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pet",
            index=models.Index(
                fields=["-created_at"], name="reservation_created_b1a69e_idx"
            ),
        ),
    ]
