# Generated by Django 5.1.5 on 2025-02-27 05:02

import reservations.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0015_remove_customer_reservation_phone_63f42b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=reservations.fields.EncryptedTextField(
                blank=True, null=True, verbose_name="주소"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=reservations.fields.EncryptedEmailField(
                blank=True, max_length=254, null=True, verbose_name="이메일"
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="breed",
            field=reservations.fields.EncryptedCharField(
                blank=True, max_length=100, null=True, verbose_name="품종"
            ),
        ),
    ]
