# Generated by Django 5.1.5 on 2025-02-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="위젯 이름")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("reservation_stats", "예약 통계"),
                            ("memorial_room_status", "추모실 현황"),
                            ("recent_reservations", "최근 예약"),
                            ("calendar", "일정 캘린더"),
                            ("staff_workload", "직원 배정 현황"),
                            ("alerts", "알림"),
                        ],
                        max_length=50,
                        verbose_name="위젯 타입",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화 여부")),
                ("position", models.IntegerField(default=0, verbose_name="표시 순서")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "대시보드 위젯",
                "verbose_name_plural": "대시보드 위젯 목록",
                "ordering": ["position"],
            },
        ),
    ]
