# Generated by Django 5.1.5 on 2025-01-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_level',
            field=models.IntegerField(choices=[(1, '지도사'), (2, '관리자'), (3, '슈퍼관리자')], default=1, help_text='1: 지도사, 2: 관리자, 3: 슈퍼관리자', verbose_name='권한 레벨'),
        ),
    ]
