# Generated by Django 5.1.5 on 2025-02-01 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('draft', '임시저장'), ('pending', '승인대기'), ('approved', '승인완료'), ('ordered', '발주완료'), ('received', '입고완료'), ('cancelled', '취소')], max_length=20, verbose_name='이전 상태')),
                ('to_status', models.CharField(choices=[('draft', '임시저장'), ('pending', '승인대기'), ('approved', '승인완료'), ('ordered', '발주완료'), ('received', '입고완료'), ('cancelled', '취소')], max_length=20, verbose_name='변경 상태')),
                ('change_type', models.CharField(choices=[('draft_to_pending', '임시저장 → 승인대기'), ('pending_to_approved', '승인대기 → 승인완료'), ('approved_to_ordered', '승인완료 → 발주완료'), ('ordered_to_received', '발주완료 → 입고완료'), ('to_cancelled', '취소')], max_length=20, verbose_name='변경 유형')),
                ('notes', models.TextField(blank=True, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_histories', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': '발주서 이력',
                'verbose_name_plural': '발주서 이력 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase_order', 'created_at'], name='inventory_p_purchas_30e9e3_idx'), models.Index(fields=['change_type', 'created_at'], name='inventory_p_change__03da51_idx')],
            },
        ),
    ]
