# Generated by Django 5.1.5 on 2025-02-01 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_purchaseorderhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='inventory_p_order_n_ff9797_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorder',
            name='inventory_p_status_1b7ac0_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='expected_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='notes',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승인일'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='발주일시'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_orders', to=settings.AUTH_USER_MODEL, verbose_name='발주자'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입고일시'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_orders', to=settings.AUTH_USER_MODEL, verbose_name='입고자'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_orders', to=settings.AUTH_USER_MODEL, verbose_name='승인자'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='발주번호'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier', verbose_name='공급업체'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='총액'),
        ),
    ]
