# Generated by Django 5.1.5 on 2025-02-01 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_purchaseorder_inventory_p_order_n_ff9797_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchaseorderhistory',
            name='inventory_p_purchas_30e9e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchaseorderhistory',
            name='inventory_p_change__03da51_idx',
        ),
        migrations.RemoveField(
            model_name='purchaseorderhistory',
            name='change_type',
        ),
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='처리자'),
        ),
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='처리일시'),
        ),
        migrations.AlterField(
            model_name='purchaseorderhistory',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='inventory.purchaseorder', verbose_name='발주서'),
        ),
    ]
