# Generated by Django 5.1.5 on 2025-02-02 06:54

from django.db import migrations, models
from django.utils import timezone
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_purchaseorderhistory_inventory_p_purchas_30e9e3_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='발주번호'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(auto_now_add=True, verbose_name='발주일'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True, verbose_name='예상 입고일'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='비고'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='총 금액'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(on_delete=deletion.PROTECT, related_name='created_purchase_orders', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=deletion.PROTECT, related_name='approved_purchase_orders', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=deletion.PROTECT, related_name='ordered_purchase_orders', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=deletion.PROTECT, related_name='received_purchase_orders', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ordered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='발주일'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입고일'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
    ]
