# Generated by Django 5.1.5 on 2025-02-02 07:19

from django.db import migrations, models

def set_change_type(apps, schema_editor):
    PurchaseOrderHistory = apps.get_model('inventory', 'PurchaseOrderHistory')
    for history in PurchaseOrderHistory.objects.all():
        if history.to_status == 'cancelled':
            history.change_type = 'to_cancelled'
        else:
            change_mapping = {
                ('draft', 'pending'): 'draft_to_pending',
                ('pending', 'approved'): 'pending_to_approved',
                ('approved', 'ordered'): 'approved_to_ordered',
                ('ordered', 'received'): 'ordered_to_received',
            }
            history.change_type = change_mapping.get((history.from_status, history.to_status), 'draft_to_pending')
        history.save()

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20250202_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderhistory',
            name='change_type',
            field=models.CharField(choices=[('draft_to_pending', '임시저장 → 승인대기'), ('pending_to_approved', '승인대기 → 승인완료'), ('approved_to_ordered', '승인완료 → 발주완료'), ('ordered_to_received', '발주완료 → 입고완료'), ('to_cancelled', '취소')], default='draft_to_pending', max_length=20, verbose_name='변경 유형'),
            preserve_default=False,
        ),
        migrations.RunPython(set_change_type),
    ]
