# Generated by Django 5.1.5 on 2025-02-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_auto_20250202_1619"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="notes",
            field=models.TextField(blank=True, verbose_name="비고"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
    ]
