# Generated by Django 5.1.5 on 2025-02-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial_rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorialroom",
            name="operating_hours",
            field=models.CharField(
                help_text="예: 09:00-18:00", max_length=100, verbose_name="이용시간"
            ),
        ),
    ]
