# Generated by Django 5.1.5 on 2025-02-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memorial_rooms", "0002_alter_memorialroom_operating_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="memorialroom",
            name="current_status",
            field=models.CharField(
                choices=[("available", "사용가능"), ("in_use", "사용중"), ("reserved", "예약중")],
                default="available",
                max_length=20,
                verbose_name="현재 상태",
            ),
        ),
    ]
