# Generated by Django 5.1.5 on 2025-02-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_remove_purchaseorderhistory_inventory_p_purchas_30e9e3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='패키지명')),
                ('description', models.TextField(verbose_name='설명')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='기본 가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '장례 패키지',
                'verbose_name_plural': '장례 패키지 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PremiumLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='프리미엄 라인명')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '프리미엄 라인',
                'verbose_name_plural': '프리미엄 라인 목록',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='옵션명')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
            ],
            options={
                'verbose_name': '추가 옵션',
                'verbose_name_plural': '추가 옵션 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='필수 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('default_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='funeral.funeralpackage')),
            ],
            options={
                'verbose_name': '패키지 구성 품목',
                'verbose_name_plural': '패키지 구성 품목 목록',
                'unique_together': {('package', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PackageItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='추가 가격')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('package_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='funeral.packageitem')),
            ],
            options={
                'verbose_name': '패키지 품목 옵션',
                'verbose_name_plural': '패키지 품목 옵션 목록',
                'ordering': ['additional_price'],
            },
        ),
        migrations.CreateModel(
            name='PremiumLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('premium_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='funeral.premiumline')),
            ],
            options={
                'verbose_name': '프리미엄 라인 구성 품목',
                'verbose_name_plural': '프리미엄 라인 구성 품목 목록',
                'unique_together': {('premium_line', 'category')},
            },
        ),
    ]
